version: '3.7'

services:
  team-wetrekking:
    image: asia.gcr.io/wetrekking-367408/team-wetrekking-develop:1.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/myfolder/src
    env_file:
      - ./.env.dev
    ports:
      - 3000:3000
