version: '3.7'

services:
  wetrekking-prod:
    image: asia.gcr.io/wetrekking-367408/team-wetrekking-prod:1.2
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    #    env_file:
    #      - ./.env.prod
    ports:
      - 3000:3000
