- pipeline.id: mountain
  pipeline.workers: 1
  path.config: '/usr/share/logstash/pipeline/mountain.conf'

- pipeline.id: crewBoard
  pipeline.workers: 1
  path.config: '/usr/share/logstash/pipeline/crewBoard.conf'
#
# - pipeline.id: mountain
#   pipeline.workers: 1
#   path.config: '/home/wetrekking09/offline_9th_team02_server/elk/logstash'
